### ISSUE TITLE
Unable to download the book

### ISSUE THREAD

**Issue by syeds-git** [mikebranstein/TheNativeScriptBook#9]
I read that the book is available for free however the link: https://nativescript.org/get-the-nativescript-book/#

does not have a downloadable book. Would this be fixed soon?

**Comment by NickBranstein** [comment]
Thanks for you message - we don't manage NativeScript.org but I can reach out to someone and see if we can get that link fixed.

**Comment by mikebranstein** [comment]
Drop me an email at mike dot branstein at gmail d0t c0m. I'll get you a copy.

**Comment by mikebranstein** [comment]
Not sure why I didn't think of this before. I've added the PDF and epub files to the repo. Enjoy!

**Comment by DevotionGeo** [comment]
Which version of the NativeScript this book uses?

**Comment by mikebranstein** [comment]
Thanks, @DevotionGeo. The book was authored against NativeScript v4.1 and has not been updated past v4.1.

**Comment by DevotionGeo** [comment]
@mikebranstein You're welcome and thank you! :)
